/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in installed projects. It is committed here
// so the scaffold type-checks consistently after dependencies are installed.
